# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9jj2p2LJ5vrjuX5d8ACjPzY3ZNLVGlW
"""

from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
import math
import random


class Player:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
        self.z = 0
        self.ang = 0
        self.lifline = 5
        self.is_alive_checker = 1
        self.gun_l1 = 50

    def char_move_forward(self, speed=8):
        if self.is_alive_checker:
            rad = math.radians(self.ang)
            new_x = self.x + speed * math.sin(rad)
            new_y = self.y - speed * math.cos(rad)

            wall = 795
            self.x = max(min(new_x, wall), -wall)
            self.y = max(min(new_y, wall), -wall)

    def char_move_backward(self, speed=10):
        if self.is_alive_checker:
            rad = math.radians(self.ang)
            new_x = self.x - speed * math.sin(rad)
            new_y = self.y + speed * math.cos(rad)

            wall = 795
            self.x = max(min(new_x, wall), -wall)
            self.y = max(min(new_y, wall), -wall)

    def char_rotate_left(self, ang_change=5):
        if self.is_alive_checker:
            self.ang = (self.ang + ang_change) % 360

    def char_rotate_right(self, ang_change=5):
        if self.is_alive_checker:
            self.ang = (self.ang - ang_change) % 360

    def if_damage(self):
        self.lifline -= 1
        print(f"Remaining Player Life: {self.lifline}")
        if self.lifline <= 0:
            self.lifline = 0
            self.is_alive_checker = 0

    def initializer(self):
        self.x = 0
        self.y = 0
        self.z = 0
        self.ang = 0
        self.lifline = 5
        self.is_alive_checker = 1

    def design_player_structure(self):
        glPushMatrix()
        glColor3f(0.2, 0.6, 0.2)
        glTranslatef(0, 0, 35)
        glScalef(25, 15, 40)
        glutSolidCube(1)
        glPopMatrix()

        glPushMatrix()
        glColor3f(1.0, 0.8, 0.6)
        glTranslatef(12, -15, 45)
        glRotatef(90, 1, 0, 0)
        gluCylinder(gluNewQuadric(), 8, 4, 30, 16, 16)
        glPopMatrix()

        glPushMatrix()
        glColor3f(1.0, 0.8, 0.6)
        glTranslatef(-12, -15, 45)
        glRotatef(90, 1, 0, 0)
        gluCylinder(gluNewQuadric(), 8, 4, 30, 16, 16)
        glPopMatrix()

        glPushMatrix()
        glColor3f(0.8, 0.8, 0.8)
        glTranslatef(0, -45, 45)
        glRotatef(90, 0, 0, 1)
        glRotatef(90, 0, 1, 0)
        gluCylinder(gluNewQuadric(), 8, 2, 50, 32, 32)
        glPopMatrix()

        glPushMatrix()
        glColor3f(0.1, 0.1, 0.9)
        glTranslatef(8, 0, 5)
        gluCylinder(gluNewQuadric(), 2, 8, 30, 16, 16)
        glPopMatrix()

        glPushMatrix()
        glColor3f(0.1, 0.1, 0.9)
        glTranslatef(-8, 0, 5)
        gluCylinder(gluNewQuadric(), 2, 8, 30, 16, 16)
        glPopMatrix()

        glPushMatrix()
        glColor3f(0, 0, 0)
        glTranslatef(0, 0, 65)
        gluSphere(gluNewQuadric(), 12, 20, 20)
        glPopMatrix()

    def draw(self):
        glPushMatrix()
        glTranslatef(self.x, self.y, self.z)
        glRotatef(self.ang, 0, 0, 1)

        if not self.is_alive_checker:
            glRotatef(90, 1, 0, 0)

        self.design_player_structure()
        glPopMatrix()

    def first_person_view(self):
        arm_length = 25
        glPushMatrix()
        glColor3f(1.0, 0.8, 0.6)
        glTranslatef(12, 0, 50)
        glRotatef(90, 1, 0, 0)
        gluCylinder(gluNewQuadric(), 8, 4, arm_length, 16, 16)
        glPopMatrix()

        glPushMatrix()
        glColor3f(1.0, 0.8, 0.6)
        glTranslatef(-12, 0, 50)
        glRotatef(90, 1, 0, 0)
        gluCylinder(gluNewQuadric(), 8, 4, arm_length, 16, 16)
        glPopMatrix()

        glPushMatrix()
        glColor3f(0.8, 0.8, 0.8)
        glTranslatef(0, -45, 45)
        glRotatef(90, 0, 0, 1)
        glRotatef(90, 0, 1, 0)
        gluCylinder(gluNewQuadric(), 8, 2, 50, 32, 32)
        glPopMatrix()

    def gun_endpoint(self):
        rad = math.radians(self.ang)
        barrel_x = self.x + self.gun_l1 * math.sin(rad)
        barrel_y = self.y - self.gun_l1 * math.cos(rad)
        barrel_z = 50
        return barrel_x, barrel_y, barrel_z


class Enemy:
    def __init__(self, x, y, arena_size=850):
        self.x = x
        self.y = y
        self.z = 0
        self.arena_size = arena_size
        self.b_radi = 35
        self.h_radi = 18
        self.pulse_ph = random.uniform(0, 360)
        self.speed = 0.25

    def update_pulse(self):
        self.pulse_ph = (self.pulse_ph + 1) % 360

    def get_current_stats(self):
        return 0.7 + abs(math.sin(math.radians(self.pulse_ph))) / 2

    def mov_and_attack_towards_player(self, player_x, player_y):
        if abs(self.x - player_x) > 1:
            self.x += self.speed if abs(self.x + 1 - player_x) < abs(self.x - player_x) else -self.speed
        if abs(self.y - player_y) > 1:
            self.y += self.speed if abs(self.y + 1 - player_y) < abs(self.y - player_y) else -self.speed

    def player_colide_enemy(self, player_x, player_y):
        dist = math.sqrt((self.x - player_x)**2 + (self.y - player_y)**2)
        scale = self.get_current_stats()
        enemy_radius = self.b_radi * scale
        player_radius = 25
        return dist < (enemy_radius + player_radius)

    def bullet_hit_enemy(self, bullet_x, bullet_y):
        dist = math.sqrt((self.x - bullet_x)**2 + (self.y - bullet_y)**2)
        scale = self.get_current_stats()
        enemy_radius = self.b_radi * scale
        bullet_radius = 10
        return dist < (enemy_radius + bullet_radius)

    def respawn_enemy_in_field(self):
        while True:
            self.x = random.randint(-int(self.arena_size * 0.8), int(self.arena_size * 0.8))
            self.y = random.randint(-int(self.arena_size * 0.8), int(self.arena_size * 0.8))

            distance_from_center = math.sqrt(self.x**2 + self.y**2)
            if distance_from_center > 200:
                break

        self.pulse_ph = random.uniform(0, 360)

    def draw(self):
        glPushMatrix()
        glTranslatef(self.x, self.y, self.z)

        scale = self.get_current_stats()
        glScalef(scale, scale, scale)

        glPushMatrix()
        glColor3f(1.0, 0.0, 0.0)
        glTranslatef(0, 0, self.b_radi)
        glutSolidSphere(self.b_radi, 20, 20)
        glPopMatrix()

        glPushMatrix()
        glColor3f(0.0, 0.0, 0.0)
        glTranslatef(0, 0, self.b_radi * 2)
        glutSolidSphere(self.h_radi, 15, 15)
        glPopMatrix()

        glPopMatrix()


class Arena:
    def __init__(self):
        self.size = 795
        self.div = 5
        self.tile_sz = self.size / self.div
        self.wall_h1 = 135
        self.wall_th1 = 14

    def grid_tiles(self):
        glBegin(GL_QUADS)
        for i in range(-self.div, self.div):
            for j in range(-self.div, self.div):
                if (i + j) % 2 == 0:
                    glColor3f(1, 1, 1)
                else:
                    glColor3f(0.7, 0.5, 0.95)

                x1 = i * self.tile_sz
                y1 = j * self.tile_sz
                x2 = (i + 1) * self.tile_sz
                y2 = (j + 1) * self.tile_sz

                glVertex3f(x1, y1, 0)
                glVertex3f(x2, y1, 0)
                glVertex3f(x2, y2, 0)
                glVertex3f(x1, y2, 0)
        glEnd()

    def boundary(self, x1, y1, x2, y2, color):
        glColor3f(color[0], color[1], color[2])

        dx = x2 - x1
        dy = y2 - y1
        length = (dx**2 + dy**2)**0.5

        if length > 0:
            nx = -dy / length * self.wall_th1 / 2
            ny = dx / length * self.wall_th1 / 2
        else:
            nx, ny = 0, 0

        glBegin(GL_QUADS)
        glVertex3f(x1 + nx, y1 + ny, 0)
        glVertex3f(x2 + nx, y2 + ny, 0)
        glVertex3f(x2 + nx, y2 + ny, self.wall_h1)
        glVertex3f(x1 + nx, y1 + ny, self.wall_h1)

        glVertex3f(x1 - nx, y1 - ny, 0)
        glVertex3f(x2 - nx, y2 - ny, 0)
        glVertex3f(x2 - nx, y2 - ny, self.wall_h1)
        glVertex3f(x1 - nx, y1 - ny, self.wall_h1)

        glColor3f(min(color[0] + 0.1, 1), min(color[1] + 0.1, 1), min(color[2] + 0.1, 1))
        glVertex3f(x1 + nx, y1 + ny, self.wall_h1)
        glVertex3f(x2 + nx, y2 + ny, self.wall_h1)
        glVertex3f(x2 - nx, y2 - ny, self.wall_h1)
        glVertex3f(x1 - nx, y1 - ny, self.wall_h1)

        glColor3f(color[0], color[1], color[2])
        glVertex3f(x1 + nx, y1 + ny, 0)
        glVertex3f(x1 - nx, y1 - ny, 0)
        glVertex3f(x1 - nx, y1 - ny, self.wall_h1)
        glVertex3f(x1 + nx, y1 + ny, self.wall_h1)

        glVertex3f(x2 + nx, y2 + ny, 0)
        glVertex3f(x2 - nx, y2 - ny, 0)
        glVertex3f(x2 - nx, y2 - ny, self.wall_h1)
        glVertex3f(x2 + nx, y2 + ny, self.wall_h1)
        glEnd()

    def boundary_m(self):
        si1 = self.size
        self.boundary(-si1, si1, si1, si1, (0, 0, 1))
        self.boundary(-si1, -si1, si1, -si1, (1, 1, 1))
        self.boundary(-si1, -si1, -si1, si1, (0, 1, 1))
        self.boundary(si1, -si1, si1, si1, (0, 1, 0))

    def draw(self):
        self.grid_tiles()
        self.boundary_m()


class Bullet:
    def __init__(self, x, y, z, ang):
        self.x = x
        self.y = y
        self.z = z
        self.ang = ang
        self.speed = 20
        self.size = 10
        self.active = 1

        rad = math.radians(ang)
        self.dx = math.sin(rad)
        self.dy = -math.cos(rad)

    def update(self):
        if self.active:
            self.x += self.dx * self.speed
            self.y += self.dy * self.speed

    def check_out_of_range(self, arena_size=850):
        return abs(self.x) >= arena_size or abs(self.y) >= arena_size

    def draw(self):
        if self.active:
            glPushMatrix()
            glColor3f(1.0, 0.0, 0.0)
            glTranslatef(self.x, self.y, 50)
            glutSolidCube(self.size)
            glPopMatrix()


class Game_play:
    def __init__(self):
        self.arena = Arena()
        self.player = Player(0, 0)
        self.enemies = []
        self.bullets = []
        self.score = 0
        self.bullets_missed = 0
        self.camera_mode = 0
        self.fovY = 120
        self.cheat_mode_checker = 0
        self.auto_gun_follow = 0
        self.camera_pos = [0, 680, 500, 0]
        self.locked_camera_pos = None

    def initialize_game(self):
        self.player.initializer()
        self.bullets.clear()
        self.enemies.clear()

        for i in range(5):
            enemy = Enemy(random.randint(-650, 650), random.randint(-650, 650), self.arena.size)
            self.enemies.append(enemy)

        self.score = 0
        self.bullets_missed = 0
        self.camera_mode = 0
        self.cheat_mode_checker = 0
        self.auto_gun_follow = 0
        self.camera_pos = [0, 680, 500, 0]
        self.locked_camera_pos = None

    def draw_text(self, x, y, text, font=GLUT_BITMAP_HELVETICA_18):
        glColor3f(1, 1, 1)
        glMatrixMode(GL_PROJECTION)
        glPushMatrix()
        glLoadIdentity()
        gluOrtho2D(0, 1000, 0, 800)
        glMatrixMode(GL_MODELVIEW)
        glPushMatrix()
        glLoadIdentity()
        glRasterPos2f(x, y)
        for ch in text:
            glutBitmapCharacter(font, ord(ch))
        glPopMatrix()
        glMatrixMode(GL_PROJECTION)
        glPopMatrix()
        glMatrixMode(GL_MODELVIEW)

    def fire_bullet(self):
        if self.player.is_alive_checker:
            barrel_x, barrel_y, barrel_z = self.player.gun_endpoint()
            bullet = Bullet(barrel_x, barrel_y, barrel_z, self.player.ang)
            self.bullets.append(bullet)
            print("Player Bullet Fired!")

    def is_enemy_in_line_of_sight(self, player_ang, player_x, player_y, enemy_x, enemy_y, limit=1.5):
        dx = abs(enemy_x - player_x)
        dy = abs(enemy_y - player_y)

        if dx == 0:
            dx = 0.001

        vision_to_enemy_incoming = math.degrees(math.atan(dy / dx))

        if enemy_x < player_x and player_y <= enemy_y:
            vision_to_enemy_incoming = 180 - vision_to_enemy_incoming
        elif enemy_x < player_x and enemy_y < player_y:
            vision_to_enemy_incoming = 180 + vision_to_enemy_incoming
        elif player_x < enemy_x and enemy_y < player_y:
            vision_to_enemy_incoming = -vision_to_enemy_incoming

        vision_to_enemy_incoming = (vision_to_enemy_incoming + 90) % 360

        return abs(abs(vision_to_enemy_incoming) - abs(player_ang)) < limit

    def setup_camera(self):
        glMatrixMode(GL_PROJECTION)
        glLoadIdentity()
        gluPerspective(self.fovY, 1.25, 0.1, 1500)
        glMatrixMode(GL_MODELVIEW)
        glLoadIdentity()

        if self.camera_mode == 0:

            x, y, z, t = self.camera_pos
            gluLookAt(x, y, z, 0, 0, 0, 0, 0, 1)
        elif self.camera_mode == 1:

            rad = math.radians(self.player.ang)
            back_distance = -30
            camera_height = 100

            if self.cheat_mode_checker and not self.auto_gun_follow:

                if self.locked_camera_pos:
                    cam_x, cam_y, cam_z, look_x, look_y, look_z = self.locked_camera_pos
                    gluLookAt(cam_x, cam_y, cam_z, look_x, look_y, look_z, 0, 0, 1)
                else:
                    cam_x = self.player.x + back_distance * math.sin(rad)
                    cam_y = self.player.y - back_distance * math.cos(rad)
                    cam_z = self.player.z + camera_height

                    look_distance = 150
                    look_x = self.player.x + look_distance * math.sin(rad)
                    look_y = self.player.y - look_distance * math.cos(rad)
                    look_z = self.player.z + 50

                    self.locked_camera_pos = [cam_x, cam_y, cam_z, look_x, look_y, look_z]
                    gluLookAt(cam_x, cam_y, cam_z, look_x, look_y, look_z, 0, 0, 1)
            elif self.auto_gun_follow:

                look_distance = 200
                look_x = self.player.x + look_distance * math.sin(rad)
                look_y = self.player.y - look_distance * math.cos(rad)
                look_z = 20

                gluLookAt(self.player.x, self.player.y, self.player.z + 65,
                         look_x, look_y, look_z, 0, 0, 1)
            else:

                cam_x = self.player.x + back_distance * math.sin(rad)
                cam_y = self.player.y - back_distance * math.cos(rad)
                cam_z = self.player.z + camera_height

                look_distance = 150
                look_x = self.player.x + look_distance * math.sin(rad)
                look_y = self.player.y - look_distance * math.cos(rad)
                look_z = self.player.z + 50

                gluLookAt(cam_x, cam_y, cam_z, look_x, look_y, look_z, 0, 0, 1)

    def update_game(self):
        if self.bullets_missed >= 10 and self.player.is_alive_checker:
            self.player.is_alive_checker = 0
            return

        if self.player.lifline <= 0 and self.player.is_alive_checker:
            self.player.is_alive_checker = 0
            return

        if not self.player.is_alive_checker:
            return

        if self.cheat_mode_checker:
            self.player.ang = (self.player.ang + 3) % 360
            for enemy in self.enemies:
                if self.is_enemy_in_line_of_sight(self.player.ang, self.player.x, self.player.y, enemy.x, enemy.y):
                    self.fire_bullet()
                    break

        for enemy in self.enemies:
            enemy.update_pulse()
            enemy.mov_and_attack_towards_player(self.player.x, self.player.y)

            if enemy.player_colide_enemy(self.player.x, self.player.y):
                self.player.if_damage()
                enemy.respawn_enemy_in_field()

                if self.player.lifline <= 0:
                    self.player.is_alive_checker = 0
                    return

        bullets_to_remove = []
        for bullet in self.bullets:
            bullet.update()

            if bullet.check_out_of_range(self.arena.size):
                bullets_to_remove.append(bullet)
                self.bullets_missed += 1
                print(f"Bullet missed: {self.bullets_missed}")

                if self.bullets_missed >= 10:
                    self.player.is_alive_checker = 0
                    return
                continue

            hit = 0
            for enemy in self.enemies:
                if enemy.bullet_hit_enemy(bullet.x, bullet.y):
                    bullets_to_remove.append(bullet)
                    enemy.respawn_enemy_in_field()
                    self.score += 1
                    hit = 1
                    break

            if hit:
                continue

        for bullet in bullets_to_remove:
            if bullet in self.bullets:
                self.bullets.remove(bullet)

    def render_callback(self):
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
        glLoadIdentity()
        glViewport(0, 0, 1000, 800)

        self.setup_camera()
        self.arena.draw()

        if self.camera_mode == 1:
            if self.auto_gun_follow:
                glPushMatrix()
                glTranslatef(self.player.x, self.player.y, self.player.z)
                glRotatef(self.player.ang, 0, 0, 1)
                self.player.first_person_view()
                glPopMatrix()
            else:

                self.player.draw()


        if self.camera_mode == 0:
            self.player.draw()

        if self.player.is_alive_checker:
            for enemy in self.enemies:
                enemy.draw()

            for bullet in self.bullets:
                bullet.draw()

        if not self.player.is_alive_checker:
            self.draw_text(10, 770, f"Game is Over. Your Score is {self.score}.")
            self.draw_text(10, 745, 'Press "R" to RESTART the Game.')
        else:
            self.draw_text(10, 770, f"Player Life Remaining: {self.player.lifline}")
            self.draw_text(10, 745, f"Game Score: {self.score}")
            self.draw_text(10, 720, f"Player Bullet Missed: {self.bullets_missed}")

        glutSwapBuffers()


game = None


def keyboardListener(key, x, y):
    if key == b'w':
        game.player.char_move_forward()
    if key == b's':
        game.player.char_move_backward()

    if not game.cheat_mode_checker:
        if key == b'a':
            game.player.char_rotate_left()
        if key == b'd':
            game.player.char_rotate_right()

    if key == b'c':
        game.cheat_mode_checker = not game.cheat_mode_checker

        if not game.cheat_mode_checker:
            game.locked_camera_pos = None
            game.auto_gun_follow = 0


    if key == b'v':
        if game.cheat_mode_checker and game.camera_mode == 1:
            game.auto_gun_follow = not game.auto_gun_follow


    if key == b'r':
        game.initialize_game()

    glutPostRedisplay()


def specialKeyListener(key, x, y):

    if game.camera_mode != 0:
        return

    r = 680
    cam_x, cam_y, cam_z, angle = game.camera_pos

    if key == GLUT_KEY_UP:
        cam_z += 20
    elif key == GLUT_KEY_DOWN:
        cam_z -= 20
    elif key == GLUT_KEY_LEFT:
        angle = (angle + 2) % 360
    elif key == GLUT_KEY_RIGHT:
        angle = (angle - 2) % 360

    cam_x = math.sin(math.radians(angle)) * r
    cam_y = math.cos(math.radians(angle)) * r
    game.camera_pos = [cam_x, cam_y, cam_z, angle]

    glutPostRedisplay()


def mouseListener(button, state, x, y):

    if button == GLUT_LEFT_BUTTON and state == GLUT_DOWN:
        game.fire_bullet()

    if button == GLUT_RIGHT_BUTTON and state == GLUT_DOWN:
        game.camera_mode = 1 - game.camera_mode

        game.locked_camera_pos = None
        game.auto_gun_follow = 0

    glutPostRedisplay()


def idle():
    game.update_game()
    glutPostRedisplay()


def showScreen():
    game.render_callback()


def main():
    global game

    glutInit()
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
    glutInitWindowSize(1000, 800)
    glutInitWindowPosition(0, 0)
    glutCreateWindow(b"3D Shooting Game")
    game = Game_play()
    game.initialize_game()

    glutDisplayFunc(showScreen)
    glutKeyboardFunc(keyboardListener)
    glutSpecialFunc(specialKeyListener)
    glutMouseFunc(mouseListener)
    glutIdleFunc(idle)

    glutMainLoop()


if __name__ == "__main__":
    main()